apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: /
  newName: /
- name: roheejae/ticketaka-auth
  newName: roheejae/ticketaka-auth
  newTag: v0.0.5
- name: roheejae/ticketaka-member
  newName: roheejae/ticketaka-member

resources:
- ./resources
