apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: member
  name: member-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8081"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mariadb://member-db-svc:3306/member
        - name: SPRING_DATASOURCE_USERNAME
          value: user
        - name: SPRING_DATASOURCE_PASSWORD
          value: user
        - name: REDIS_URL
          value: redis-svc
        - name: REDIS_PORT
          value: "6379" 
        image: roheejae/ticketaka_member:1.1
        name: member
        ports:
        - containerPort: 8081
          name: member
        volumeMounts:
        - name: tz-seoul
          mountPath: /etc/localtime
      volumes:
      - name: tz-seoul
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: member
  name: member-svc
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8081
  selector:
    app: member