resources:
- ns-member.yaml
- member-cm.yaml
- member-secret.yaml
- member.yaml
- member-redis.yaml
- harborscrt-member.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: harbor.hotsun.store/ticketaka/ticketaka-member
  newTag: v0.0.2
- name: roheejae/ticketaka-member
  newTag: v0.0.47
