resources:
- ns-member.yaml
- member-cm.yaml
- member-db.yaml
- member.yaml
- member-secret.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: roheejae/ticketaka-member
  newTag: v0.0.14
