apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: member
  name: member-deploy
  namespace: ticketaka-member
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: member-cm
              key: SERVER_PORT
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: member-cm
              key: SPRING_DATASOURCE_URL        
        - name: RESERVATION_URL
          valueFrom:
            configMapKeyRef:
              name: member-cm
              key: RESERVATION_URL
        - name: RESERVATION_PORT
          valueFrom: 
            configMapKeyRef:
              name: member-cm
              key: RESERVATION_PORT
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: member-cm
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: member-cm
              key: SPRING_DATASOURCE_PASSWORD
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: member-secret
              key: PRIVATE_KEY
        image: roheejae/ticketaka-member:v0.0.14
        name: member
        ports:
        - containerPort: 8081
          name: member
        volumeMounts:
        - name: tz-seoul
          mountPath: /etc/localtime
      volumes:
      - name: tz-seoul
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
      restartPolicy: Always
  # strategy:
  #   canary:
  #     maxSurge: "33%"    # canary 배포로 생성할 pod의 비율
  #     maxUnavailable: 0  # 업데이트 될 때 사용할 수 없는 pod의 최대 수
  #     steps:
  #     - setWeight: 33    # 카나리로 배포된 서버로 전송해야될 트래픽 비율
  #     - pause: {}        # AutoPromotion Time (하단 설명 참조)
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: member
  name: member-svc
  namespace: ticketaka-member
spec:
  type: ClusterIP
  ports:
  - port: 8081
  selector:
    app: member