apiVersion: v1
kind: ConfigMap
metadata:
  name: member-cm
  namespace: ticketaka-member
data:
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: jdbc:mariadb://10.0.161.50:3306/member?serverTimezone=Asia/Seoul
  RESERVATION_URL: reservation-svc.ticketaka-reservation.svc.cluster.local
  RESERVATION_PORT: "8080"
  SPRING_DATASOURCE_USERNAME: user
  SPRING_DATASOURCE_PASSWORD: user
  RABBITMQ_HOST: reservation-rabbitmq-cluster-nodes.ticketaka-reservation.svc.cluster.local
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: user
  RABBITMQ_PASSWORD: user
  REDIS_HOST: redis-svc
  REDIS_PORT: "6379"
