resources:
- ns-ticketaka-front.yaml
- ticketaka-front-cm.yaml
- ticketaka-front-secret.yaml
- ticketaka-front-deploy.yaml
- ticketaka-front-svc.yaml
- ticketaka-front-ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: harbor.hotsun.store/ticketaka/ticketaka-front
  newTag: v0.0.4
- name: roheejae/ticketaka-front
  newTag: v0.0.83
