apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: ticketaka-front
  name: ticketaka-front
  namespace: ticketaka-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketaka-front
  template:
    metadata:
      labels:
        app: ticketaka-front
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - env:
        - name: REACT_APP_BASE_URL
          value: http://192.168.56.100:30030
        - name: REACT_APP_NAVER_SECRET
          valueFrom:
            secretKeyRef:
              key: REACT_APP_NAVER_SECRET
              name: ticketaka-front-secret
        - name: REACT_APP_KOPIS_SECRET
          valueFrom:
            secretKeyRef:
              key: REACT_APP_KOPIS_SECRET
              name: ticketaka-front-secret
        image: harbor.hotsun.store/ticketaka/ticketaka-front:v0.0.5
        imagePullPolicy: Always
        name: ticketaka-front
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: ticketaka-front-cm
          readOnly: true
          subPath: default.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: ticketaka-front-cm
        name: ticketaka-front-cm