apiVersion: argoproj.io/v1alpha1
kind: Rollout # Rollout으로 생성
metadata:
  name: ticketaka-front
  namespace: ticketaka-front
  labels:
    app: ticketaka-front
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ticketaka-front
  template:
    metadata:
      labels:
        app: ticketaka-front
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: ticketaka-front
        image: harbor.hotsun.store/ticketaka/ticketaka-front:v0.0.46
        resources:
          requests:
            cpu: 80
          limits:
            cpu: 80
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
          name: ticketaka-front-cm
        env:
        - name: REACT_APP_BASE_URL
          value: http://hotsun.store # 여기 주소 바꿔주세염
        - name: REACT_APP_NAVER_SECRET
          valueFrom:
            secretKeyRef:
              name: ticketaka-front-secret
              key: REACT_APP_NAVER_SECRET
        - name: REACT_APP_KOPIS_SECRET
          valueFrom:
            secretKeyRef:
              name: ticketaka-front-secret
              key: REACT_APP_KOPIS_SECRET
      volumes:
      - name: ticketaka-front-cm
        configMap:
          name: ticketaka-front-cm
  strategy:
    canary:
      maxSurge: "100%"    # canary 배포로 생성할 pod의 비율
      maxUnavailable: 0  # 업데이트 될 때 사용할 수 없는 pod의 최대 수
      steps:
      - setWeight: 100    # 카나리로 배포된 서버로 전송해야될 트래픽 비율
      - pause: { duration: 30m }        # AutoPromotion Time (하단 설명 참조)
