apiVersion: v1
kind: Service
metadata:
  name: ticketaka-front-svc
  namespace: ticketaka-front
spec:
  selector:
    app: ticketaka-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort