apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ticketaka-front
  name: ticketaka-front-cm
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        #access_log  /var/log/nginx/host.access.log  main;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.html;
            try_files $uri $uri/ /index.html =404;
        }

        location /api {
            proxy_pass http://kopis.or.kr/openApi/restful/boxoffice;
        }

        location /member {
            proxy_pass http://192.168.56.100:32132; # 주소 변경!
        }

        location /performance {
            proxy_pass http://192.168.56.100:32132; # 주소 변경!
        }

        location /reservation {
            proxy_pass http://192.168.56.100:32132; # 주소 변경!
        }


        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }