apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: front-deploy-hpa
  namespace: ticketaka-front
spec:
  maxReplicas: 3
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80