apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketaka-front
  namespace: ticketaka-front
  labels:
    app: ticketaka-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticketaka-front
  template:
    metadata:
      labels:
        app: ticketaka-front
    spec:
      containers:
      - name: ticketaka-front
        image: roheejae/ticketaka-front:v0.0.37
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        # volumeMounts:
        # - mountPath: /etc/nginx/conf.d/default.conf
        #   subPath: default.conf
        #   readOnly: true
        #   name: ticketaka-front-cm
        env:
        - name: REACT_APP_BASE_URL
          value: http://192.168.56.100:30030 # 여기 주소 바꿔주세염
        - name: REACT_APP_NAVER_SECRET
          valueFrom:
            secretKeyRef:
              name: ticketaka-front-secret
              key: REACT_APP_NAVER_SECRET
        - name: REACT_APP_KOPIS_SECRET
          valueFrom:
            secretKeyRef:
              name: ticketaka-front-secret
              key: REACT_APP_KOPIS_SECRET
      volumes:
      - name: ticketaka-front-cm
        configMap:
          name: ticketaka-front-cm