apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: harbor.hotsun.store/ticketaka/ticketaka-reservation
  newTag: v0.0.3
resources:
- cluster-operator.yml
- reservation-db.yaml
- reservation-consumer.yaml
- reservation-deploy.yaml
- reservation-rabbitmq-cluster-conf.yaml
- reservation-rabbitmq-cm.yaml
- reservation-auth-consumer.yaml
- harborscrt-rsv.yaml
