apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: reservation-deploy-sec
  namespace: ticketaka-reservation
data:
  SPRING_DATASOURCE_USERNAME: dXNlcg==
  SPRING_DATASOURCE_PASSWORD: dXNlcg==
  RABBITMQ_USERNAME: dXNlcg==
  RABBITMQ_PASSWORD: dXNlcg==
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reservation-deploy-hpa
  namespace: ticketaka-reservation
spec:
  replicas: 1
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout # Rollout으로 생성
    name: reservation-deploy
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout # Rollout으로 생성
metadata:
  labels:
    app: reservation
  name: reservation-deploy
  namespace: ticketaka-reservation
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://reservation-db-svc.ticketaka-reservation.svc.cluster.local:3306/ticketaka?serverTimezone=Asia/Seoul
            - name: RABBITMQ_HOST
              value: reservation-rabbitmq-cluster-nodes
            - name: RABBITMQ_PORT
              value: "5672"
          envFrom:
            - secretRef:
                name: reservation-deploy-sec
          image: harbor.hotsun.store/ticketaka/ticketaka-reservation:v0.0.1
          name: reservation
          ports:
            - containerPort: 8080
              name: reservation
          resources:
            limits:
              cpu: 500m
              memory: 512M
            requests:
              cpu: 100m
              memory: 256M
          volumeMounts:
            - name: tz-seoul
              mountPath: /etc/localtime
      volumes:
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
      restartPolicy: Always
  strategy:
    canary:
      maxSurge: "100%"    # canary 배포로 생성할 pod의 비율
      maxUnavailable: 0  # 업데이트 될 때 사용할 수 없는 pod의 최대 수
      steps:
      - setWeight: 100    # 카나리로 배포된 서버로 전송해야될 트래픽 비율
      - pause: { duration: 10m }        # AutoPromotion Time (하단 설명 참조)

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reservation
  name: reservation-svc
  namespace: ticketaka-reservation
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http-rsv
    targetPort: 8080
    protocol: TCP
  selector:
    app: reservation
