apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-mail-deploy-hpa
  namespace: ticketaka-reservation
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reservation-auth-mail
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservation
  name: reservation-auth-mail
  namespace: ticketaka-reservation
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: auth-mail
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: auth-mail
    spec:
      containers:
        - env:
            - name: MAIL_SERVER
              value: smtp.gmail.com
            - name: MAIL_PORT
              value: "587"
            - name: RABBITMQ_HOST
              value: reservation-rabbitmq-cluster-nodes
            - name: RABBITMQ_PORT
              value: "5672"
          envFrom:
            - secretRef:
                name: reservation-mail-sec
          image: ehdwn15100/ticketaka-auth-mail:1.7
          name: auth-mail
          resources:
            limits:
              cpu: 500m
              memory: 256M
            requests:
              cpu: 100m
              memory: 50M         
      restartPolicy: Always
