apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: reservation-mail-sec
  namespace: ticketaka-reservation
data:
  MAIL_PASSWORD: dnNwc3d0dmR5ZmRtc3RtYg==
  MAIL_USERNAME: cHJvamVjdHRpY2tldGFrYUBnbWFpbC5jb20=
  RABBITMQ_ID: dXNlcg==
  RABBITMQ_PASSWORD: dXNlcg==
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mail-deploy-hpa
  namespace: ticketaka-reservation
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reservation-mail
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservation
  name: reservation-mail
  namespace: ticketaka-reservation
spec:
  selector:
    matchLabels:
      app: mail
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: mail
    spec:
      containers:
        - env:
            - name: MAIL_SERVER
              value: smtp.gmail.com
            - name: MAIL_PORT
              value: "587"
            - name: RABBITMQ_HOST
              value: reservation-rabbitmq-cluster
            - name: RABBITMQ_PORT
              value: "5672"
          envFrom:
            - secretRef:
                name: reservation-mail-sec
          image: ehdwn15100/ticketaka-mail:1.7
          name: mail
          resources:
            limits:
              cpu: 500m
              memory: 256M
            requests:
              cpu: 100m
              memory: 256M
      restartPolicy: Always

