apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: reservation-rabbitmq-cluster
  namespace: ticketaka-reservation
spec:
  replicas: 1
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              volumeMounts:
              - name: definitions
                mountPath: /path/to/exported/
            volumes:
            - name: definitions
              configMap:
                name: definitions
  persistence:
    storage: 10Gi
    storageClassName: rabbitmq-storageclass
  rabbitmq:
    additionalConfig: |
      load_definitions = /path/to/exported/definitions.json