apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservation
  name: reservation-auth-mail
  namespace: ticketaka-reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mail
  template:
    metadata:
      labels:
        app: auth-mail
    spec:
      containers:
        - env:
            - name: MAIL_SERVER
              value: smtp.gmail.com
            - name: MAIL_PORT
              value: "465"
            - name: RABBITMQ_HOST
              value: reservation-rabbitmq-cluster-nodes
            - name: RABBITMQ_PORT
              value: "5672"
          envFrom:
            - secretRef:
                name: reservation-mail-sec
          image: ehdwn15100/ticketaka-auth-mail:1.3
          name: auth-mail
      restartPolicy: Always
