apiVersion: v1
kind: Namespace
metadata:
  name: ticketaka-info
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: info-performance-sec
  namespace: ticketaka-info
data:
  HOL_SERVICE_KEY: ZVFpZStuanFLY202enpTUndqcVQ1dTdNMXRTTWQrd2srcmRCYlMxeHpqU25lQWkxdjlHVStlamx0VWZrNXNqTTRmVkQ2Y1dKTkp3dU9zRTJBTjdtWUE9PQ==
  KOPIS_SERVICE_KEY: NWQ4ZTljNTMwYzEyNDMzMzk3Yjk0ZmMwNjkzMWJlZDI=
  DATABASE_USER: dXNlcg==
  DATABASE_PASSWORD: dXNlcg==
  DATABASE_PORT: MzMwNg==
  DATABASE_NAME: dGlja2V0YWth

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: info-performance
  namespace: ticketaka-info
spec:
  schedule: "CRON_TZ=Asia/Seoul 05 12 */1 * *"
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: info-performance
            image: roheejae/ticketaka-data:v0.0.9
            imagePullPolicy: Always
            env:
                - name: DATABASE_HOST
                  value: 10.0.161.51
            envFrom:
                - secretRef:
                    name: info-performance-sec
          restartPolicy: OnFailure