apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: /
  newName: /
- name: roheejae/ticketaka-auth
  newTag: v0.0.21
- name: roheejae/ticketaka-front
  newTag: v0.0.28
>>>>>>> 2a3b2c1371b9aed75ac321ccf3538e195f9a7f0c
- name: roheejae/ticketaka-frontend
  newTag: v0.0.0
- name: roheejae/ticketaka-member
  newTag: v0.0.9
- name: roheejae/ticketaka-performance
  newTag: v0.0.0
- name: roheejae/ticketaka-reservation
  newTag: v0.0.17
resources:
- ../../resources
