apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /
  newName: /
- name: roheejae/ticketaka-auth
  newTag: v0.0.21
- name: roheejae/ticketaka-front
  newTag: v0.0.39
- name: roheejae/ticketaka-member
  newTag: v0.0.12
- name: roheejae/ticketaka-performance
  newTag: v0.0.36
- name: roheejae/ticketaka-reservation
  newTag: v0.0.21
resources:
- ../../resources/auth
- ../../resources/front
- ../../resources/member
- ../../resources/performance
- ../../resources/reservation
