apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: /
  newName: /
- name: roheejae/ticketaka-auth
  newTag: v0.0.13
- name: roheejae/ticketaka-member
  newTag: test-member

resources:
- ../../resources
