resources:
- ns-performance.yaml
- performance-configmap.yaml
- performance-data.yaml
- performance-db.yaml
- performance-deploy.yaml
- performance-redis.yaml
- performance-secret.yaml
- performance-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization