apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: harbor.hotsun.store/ticketaka/ticketaka-data
  newTag: v0.0.22
- name: harbor.hotsun.store/ticketaka/ticketaka-performance
  newTag: v0.0.12
resources:
- ns-performance.yaml
- performance-configmap.yaml
- performance-db.yaml
- performance-deploy.yaml
- performance-redis.yaml
- performance-secret.yaml
- performance-svc.yaml
- harborscrt-prf.yaml
