apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: roheejae/ticketaka-data
  newTag: v0.0.11
- name: roheejae/ticketaka-performance
  newTag: v0.0.45
resources:
- ns-performance.yaml
- performance-configmap.yaml
- performance-deploy.yaml
- performance-redis.yaml
- performance-secret.yaml
- performance-svc.yaml
