apiVersion: v1
kind: Service
metadata:
  labels:
    app: performance
  name: performance-svc
  namespace: ticketaka-performance
spec:
  type: ClusterIP
  ports:
  - port: 8084
    name: http-prf
    targetPort: 8084
    protocol: TCP
  selector:
    app: performance
