apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: performance-deploy-hpa
  namespace: ticketaka-performance
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout # Rollout으로 생성
    name: performance-deploy
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: performance-deploy
  namespace: ticketaka-performance
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: performance
  template:
    metadata:
      labels:
        app: performance
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: performance
        image: roheejae/ticketaka-performance:v0.0.26
        ports:
        - containerPort: 8084
          name: performance
        env:
        - name: SERVER_PORT
          value: "8084"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: performance-configmap
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: performance-secret
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: performance-secret
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: performance-configmap
              key: SPRING_REDIS_HOST
        - name: SPRING_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: performance-configmap
              key: SPRING_REDIS_PORT
        - name: MEMBER_URL
          valueFrom:
            configMapKeyRef:
              name: performance-configmap
              key: MEMBER_URL
        - name: MEMBER_PORT
          valueFrom:
            configMapKeyRef:
              name: performance-configmap
              key: MEMBER_PORT
        image: harbor.hotsun.store/ticketaka/ticketaka-performance:v0.0.1
        name: performance
        ports:
        - containerPort: 8084
          name: performance
        resources:
          limits:
            cpu: 500m
            memory: 750M
          requests:
            cpu: 200m
            memory: 300M
        volumeMounts:
        - name: tz-seoul
          mountPath: /etc/localtime
      volumes:
      - name: tz-seoul
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
      restartPolicy: Always
  strategy:
    canary:
      maxSurge: "100%"    # canary 배포로 생성할 pod의 비율
      maxUnavailable: 0  # 업데이트 될 때 사용할 수 없는 pod의 최대 수
      steps:
      - setWeight: 100    # 카나리로 배포된 서버로 전송해야될 트래픽 비율
      - pause: { duration: 10m }        # AutoPromotion Time (하단 설명 참조)