apiVersion: v1
kind: ConfigMap
metadata:
  name: performance-configmap
  namespace: ticketaka-performance
data:
  SPRING_DATASOURCE_URL: jdbc:mariadb://performance-db-svc:3306/ticketaka?serverTimezone=Asia/Seoul
  SPRING_REDIS_HOST: performance-redis-svc
  SPRING_REDIS_PORT: '6379'
  RESERVATION_URL: member-svc.ticketaka-member.svc.cluster.local
  RESERVATION_PORT: '8081'
