apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: performance
  name: performance-deploy
  namespace: ticketaka-performance
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: performance
  template:
    metadata:
      labels:
        app: performance
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8084"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: performance-configmap
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: performance-secret
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: performance-secret
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: performance-configmap
              key: SPRING_REDIS_HOST
        - name: SPRING_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: performance-configmap
              key: SPRING_REDIS_PORT
        - name: RESERVATION_URL
          valueFrom:
            configMapKeyRef:
              name: performance-configmap
              key: RESERVATION_URL
        - name: RESERVATION_PORT
          valueFrom:
            configMapKeyRef:
              name: performance-configmap
              key: RESERVATION_PORT
        image: roheejae/ticketaka-performance:v0.0.26
        name: performance
        ports:
        - containerPort: 8084
          name: performance
        volumeMounts:
        - name: tz-seoul
          mountPath: /etc/localtime
      volumes:
      - name: tz-seoul
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
      restartPolicy: Always