apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: info-performance-sec
  namespace: ticketaka-performance
data:
  HOL_SERVICE_KEY: ZVFpZStuanFLY202enpTUndqcVQ1dTdNMXRTTWQrd2srcmRCYlMxeHpqU25lQWkxdjlHVStlamx0VWZrNXNqTTRmVkQ2Y1dKTkp3dU9zRTJBTjdtWUE9PQ==
  KOPIS_SERVICE_KEY: NWQ4ZTljNTMwYzEyNDMzMzk3Yjk0ZmMwNjkzMWJlZDI=
  DATABASE_USER: dXNlcg==
  DATABASE_PASSWORD: dXNlcg==
  DATABASE_PORT: MzMwNg==
  DATABASE_NAME: dGlja2V0YWth

---
apiVersion: v1
kind: Pod
metadata:
  name: info-performance
  namespace: ticketaka-performance
  labels:
    app: performance
spec:
  containers:
    - image: ehdwn15100/info_performance:1.0
      name: info-performance
      env:
        - name: DATABASE_HOST
          value: performance-db-svc
      envFrom:
        - secretRef:
            name: info-performance-sec
  restartPolicy: OnFailure