apiVersion: v1
kind: ConfigMap
metadata:
  name: performance-configmap
  namespace: ticketaka-performance
data:
  SPRING_DATASOURCE_URL: jdbc:mariadb://performance-db-svc.ticketaka-performance.svc.cluster.local:3306/ticketaka?serverTimezone=Asia/Seoul
  MEMBER_URL: member-svc.ticketaka-member.svc.cluster.local
  MEMBER_PORT: "8081"
  SPRING_REDIS_HOST: performance-redis-svc.ticketaka-performance.svc.cluster.local
  SPRING_REDIS_PORT: "6379"