apiVersion: v1
kind: PersistentVolume
metadata:
  name: performance-db-pv
  namespace: ticketaka-performance
  labels:
    type: db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/performance-db-storage/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: performance-db-pvc
  namespace: ticketaka-performance
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi


---
apiVersion: v1
kind: Service
metadata:
  name: performance-db-svc
  namespace: ticketaka-performance
  labels:
    type: db
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    type: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: db
  name: performance-db
  namespace: ticketaka-performance
spec:
  replicas: 1
  strategy:
    type:  Recreate
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      labels:
        type: db
    spec:
      containers:
      - image: mariadb:10.7.8-focal
        name: performance-db
        args:
        - --character-set-server=utf8
        - --collation-server=utf8_general_ci
        - --explicit_defaults_for_timestamp=1
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "1234"
        - name: MARIADB_DATABASE
          value: ticketaka
        - name: MARIADB_USER
          value: user
        - name: MARIADB_ROOT_HOST
          value: '%'
        - name: MARIADB_PASSWORD
          value: user
        ports:
        - containerPort: 3306
          name: performance-db
        volumeMounts:
        - name: tz-seoul
          mountPath: /etc/localtime
        - name: roll-db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: tz-seoul
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
      - name: roll-db-storage
        persistentVolumeClaim:
          claimName: performance-db-pvc